theme: jekyll-theme-cayman
title: Welcome to Dr Monica Pereira's Website

heading: Dr Monica Pereira

Heading: Lecturer in Psychology

Paragraph: I am a lecturer in Psychology at London Metropolitan University. I lead modules for level 6 in cyberpsychology and level 4 in study skills. I also teach biopsychology at level 4, 5 and clinical neuroscience at level 6.

Heading: Current Projects 
Subheading: Communication Skills Training Intervention Based on Automated Detection of Social Signals

Subheading: Exploring barriers to volunteering in the SIGCHI Community
Deputy Chair and Research Scientist

